version: 0.2
env:
  variables:
    MDTP_ENVIRONMENT: "internal-base"
    SAM_USE_CONTAINER: "--use-container"
  parameter-store:
    GITHUB_API_TOKEN: telemetry_github_token
    GITHUB_API_USER: telemetry_github_user
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - cd $(pyenv root)
      - git stash
      - git pull
      - cd -
      - pyenv install -s $(cat .python-version)
  pre_build:
    commands:
      - pip install --upgrade pip
      - pyenv global $(cat .python-version)
      - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
      - export PATH=$PATH:$HOME/.poetry/bin
      - poetry config virtualenvs.create false
      - poetry install
  build:
    commands:
      - GIT_BRANCH=${CODEBUILD_RESOLVED_SOURCE_VERSION:-default} GITHUB_API_TOKEN=${GITHUB_API_TOKEN} GITHUB_API_USER=${GITHUB_API_USER} make verify_package_and_publish
