[project]
name = "aws-lambda-ec2-launch-checks"
version = "1.0.0"
description = "An AWS Lambda that will check Goss endpoint when triggered by ASG instance launch"
authors = [{ name = "Team Telemetry", email = "telemetry@digital.hmrc.gov.uk" }]
license = "Apache 2.0"
maintainers = [{ name = "Team Telemetry", email = "telemetry@digital.hmrc.gov.uk" }]
readme = "README.md"
requires-python = ">=3.14,<3.15"

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.14",
]

dependencies = [
    "aws-lambda-powertools",
    "cryptography",
    "packaging",
    "urllib3>=2.7.0",
    "requests",
]

[dependency-groups]
dev = [
    "aws-lambda-context",
    "bandit",
    "black",
    "boto3",
    "pytest",
    "pytest-cov",
    "pytest-ruff",
    "requests-mock",
    "version-incrementor",
]

[tool.coverage.run]
source = ["./src"]

[tool.coverage.report]
fail_under = 70

[tool.pytest.ini_options]
log_cli = true
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
log_cli_level = "INFO"
log_date_format = "%Y-%m-%d %H:%M:%S"
log_format = "%(asctime)s %(levelname)s %(message)s"
log_level = "INFO"
python_files = ["tests.py", "test_*.py", "*_tests.py", "*_test.py"]
pythonpath = ". src"
addopts = [
    "--ruff",
    "--cov=./src",
    "--no-cov-on-fail",
    "-p no:warnings"
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "W"]

[tool.uv]
package = false
default-groups = "all"

[[tool.uv.index]]
name = "artifactory"
url = "https://artefacts.tax.service.gov.uk/artifactory/api/pypi/pips/simple"
default = true

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
