"""
This type stub file was generated by pyright.
"""

import os
from boto3.docs.service import ServiceDocumenter

def generate_docs(root_dir, session): # -> None:
    """Generates the reference documentation for botocore

    This will go through every available AWS service and output ReSTructured
    text files documenting each service.

    :param root_dir: The directory to write the reference files to. Each
        service's reference documentation is loacated at
        root_dir/reference/services/service-name.rst

    :param session: The boto3 session
    """
    ...

