"""
This type stub file was generated by pyright.
"""

from boto3.docs.base import BaseDocumenter

class ActionDocumenter(BaseDocumenter):
    def document_actions(self, section): # -> None:
        ...
    


def document_action(section, resource_name, event_emitter, action_model, service_model, include_signature=...): # -> None:
    """Documents a resource action

    :param section: The section to write to

    :param resource_name: The name of the resource

    :param event_emitter: The event emitter to use to emit events

    :param action_model: The model of the action

    :param service_model: The model of the service

    :param include_signature: Whether or not to include the signature.
        It is useful for generating docstrings.
    """
    ...

def document_load_reload_action(section, action_name, resource_name, event_emitter, load_model, service_model, include_signature=...): # -> None:
    """Documents the resource load action

    :param section: The section to write to

    :param action_name: The name of the loading action should be load or reload

    :param resource_name: The name of the resource

    :param event_emitter: The event emitter to use to emit events

    :param load_model: The model of the load action

    :param service_model: The model of the service

    :param include_signature: Whether or not to include the signature.
        It is useful for generating docstrings.
    """
    ...

