"""
This type stub file was generated by pyright.
"""

from botocore.docs.params import ResponseParamsDocumenter

class ResourceShapeDocumenter(ResponseParamsDocumenter):
    EVENT_NAME = ...


def document_attribute(section, service_name, resource_name, attr_name, event_emitter, attr_model, include_signature=...): # -> None:
    ...

def document_identifier(section, resource_name, identifier_model, include_signature=...): # -> None:
    ...

def document_reference(section, reference_model, include_signature=...): # -> None:
    ...

