"""
This type stub file was generated by pyright.
"""

class BaseDocumenter:
    def __init__(self, resource) -> None:
        ...
    
    @property
    def class_name(self): # -> str:
        ...
    


