"""
This type stub file was generated by pyright.
"""

def document_model_driven_resource_method(section, method_name, operation_model, event_emitter, method_description=..., example_prefix=..., include_input=..., include_output=..., exclude_input=..., exclude_output=..., document_output=..., resource_action_model=..., include_signature=...): # -> None:
    ...

