"""
This type stub file was generated by pyright.
"""

from boto3.docs.base import BaseDocumenter

class ResourceDocumenter(BaseDocumenter):
    def __init__(self, resource, botocore_session) -> None:
        ...
    
    def document_resource(self, section): # -> None:
        ...
    


class ServiceResourceDocumenter(ResourceDocumenter):
    @property
    def class_name(self):
        ...
    


