"""
This type stub file was generated by pyright.
"""

from botocore.docs.service import ServiceDocumenter as BaseServiceDocumenter

class ServiceDocumenter(BaseServiceDocumenter):
    EXAMPLE_PATH = ...
    def __init__(self, service_name, session) -> None:
        ...
    
    def document_service(self): # -> bytes:
        """Documents an entire service.

        :returns: The reStructured text of the documented service.
        """
        ...
    
    def client_api(self, section): # -> None:
        ...
    


